---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: "./gatsby-config.js"
  label: config
  read_only: true
- type: directory
  path: ''
  label: all
  create: all
  match: "**/*"
- type: heading
  label: asdfasdf
- type: directory
  path: content
  label: Content
  create: all
  match: "**/*"
upload_dir: content/assets
public_path: "/file"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
